apiVersion: v1
kind: Service
metadata:
  name: instaflow-backend
  namespace: instaflow
spec:
  type: LoadBalancer
  selector:
    app: instaflow-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  sessionAffinity: ClientIP
